name: GitHub Actions Demo
on: [push]
jobs:
  build-java:
    name: Build and Test Java Code
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: |
          cd native-image/graalvm-native-image-quick-start/demo/
          mvn --batch-mode --update-snapshots verify
      - name: Upload JAR
        uses: actions/upload-artifact@v2
        with:
          name: jar-file
          path: native-image/graalvm-native-image-quick-start/demo/target/graalvmnidemos-1.0-SNAPSHOT-jar-with-dependencies.jar
      - run: echo "👷‍  Build status ${{ job.status }}."

  build-native-image:
    name: Build and Test Java Code
    needs: build-java
    runs-on:  ubuntu-latest
    container:
      image: container-registry.oracle.com/graalvm/native-image:ol7-java11
      options: --entrypoint /bin/sh
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: jar-file
      - run |
          ls -la

#      - uses: actions/checkout@v2
#      - name: Build / Test Code
#        run: |
#          yum install -y tar zip unzip
#          yum install -y maven
#          cd native-image/graalvm-native-image-quick-start/demo
#          java -version
#          mvn -version
#          mvn clean package test
#      - run: echo "👷‍  Build status ${{ job.status }}."

#  create-release:
#    name: Create Release
#    runs-on: ubuntu-latest
#    needs: build-java
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#      - name: Create Release
#        id: create_release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
#        with:
#          tag_name: ${{ github.ref }}
#          release_name: Release ${{ github.ref }}
#          body: |
#            Changes in this Release
#            - A Test
#          draft: false
#          prerelease: false