name: GraalVM Native Reflection Tutorial Pipeline
on: [push]
jobs:
  build-java:
    name: Build and Test Java Code
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build
        run: |
          cd native-image/reflection/demo/
          ls -lar
          javac ReflectionExample.java
      - name: Upload Class files
        uses: actions/upload-artifact@v2
        with:
          name: class-files
          path: native-image/reflection/demo/*.class
      - name: Upload Native Image Config Files
        uses: actions/upload-artifact@v2
        with:
          name: config-files
          path: native-image/reflection/demo/META-INF-WORKING/native-image/reflect-config.json
      - run: echo "👷‍  Build status ${{ job.status }}."

  native:
    name: Build and Test Native Image
    needs: build-java
    runs-on:  ubuntu-latest
    container:
      image: container-registry.oracle.com/graalvm/native-image:ol7-java11
      options: --entrypoint /bin/sh
    steps:
      - uses: actions/download-artifact@v2
      - name: Build Native Executable
        run: |
          native-image -cp ./class-files --no-fallback -H:ReflectionConfigurationFiles=config-files/reflect-config.json ReflectionExample
      - run: echo "👷‍  Native build status ${{ job.status }}."
