name: GraalVM Native Reflection Tutorial Pipeline
on: [push]
jobs:
  build-java:
    name: Build and Test Java Code
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build
        run: |
          cd native-image/reflection/demo/
          javac ReflectionExample.java
      - name: Upload Class files
        uses: actions/upload-artifact@v2
        with:
          name: class-files
          path: native-image/reflection/demo/*.class
      - run: echo "👷‍  Build status ${{ job.status }}."
