name: GraalVM Native Image Quick Start Pipeline
on:
  push:
    paths:
      - 'native-image/graalvm-native-image-quick-start/lab/**'
      - '.github/workflows/github-actions-native-image-quickstart.yml'
jobs:
  build:
    name: Native Image Quickstart on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Test Java Code
        run: |
          cd native-image/graalvm-native-image-quick-start/lab/
          ./mvnw --no-transfer-progress clean package exec:exec
          ./mvnw --no-transfer-progress clean package exec:exec -Pjava_agent
          ./mvnw --no-transfer-progress package -Pnative
          ./target/file-count
