name: GitHub Actions Demo
on: [push]
jobs:
  build-java:
    name: Build & Test Java Code
    container:
      image: container-registry.oracle.com/graalvm/community:java11
    steps:
      - name: Build / Test Code
        run: |
          cd Native-Image/Quick-Start/tutorial/demo
          mvn clean package test
      - run: echo "👷‍  Build status ${{ job.status }}."

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build-native-image-quickstart
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - A Test
          draft: false
          prerelease: false