name: GitHub Actions Demo
on: [push]
jobs:
  build-java:
    name: Build and Test Java Code
    runs:
      using: 'docker'
      image: 'Dockerfiles/Dockerfile.java11'
    steps:
      - uses: actions/checkout@v2
      - name: Build / Test Code
        run: |
          cd native-image/graalvm-native-image-quick-start/demo
          java -version
          mvn -version
          mvn clean package test
      - run: echo "👷‍  Build status ${{ job.status }}."


#  create-release:
#    name: Create Release
#    runs-on: ubuntu-latest
#    needs: build-java
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#      - name: Create Release
#        id: create_release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
#        with:
#          tag_name: ${{ github.ref }}
#          release_name: Release ${{ github.ref }}
#          body: |
#            Changes in this Release
#            - A Test
#          draft: false
#          prerelease: false